version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app  # 로컬 코드 변경 시 컨테이너 내부 코드도 자동 반영
    depends_on:
      - mongo  # MongoDB가 먼저 실행되도록 설정
    command: [ "npm", "run", "dev" ]

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # MongoDB 데이터 저장소

volumes:
  mongo-data:
